spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: teste
        password: teste
    h2:
        console:
            enable: true
            path: /h2-console
    jpa:
        show-sql: true
        hibernate:
            format_sql: true
        
